### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by EvaKaul** [industrial-edge/iectl-workflow#20]
The link to the official docu is broken - see here:

https://github.com/industrial-edge/iectl-workflow/blob/main/README.md

"More information about the tool as well as the official documentation can be found [here]"

Broken link: https://industrial-edge.io/developer/platform/references/iectl/index.html
Correct link: https://docs.eu1.edge.siemens.cloud/apis_and_references/iectl/index.html

**Comment by paveel-h** [comment]
Link fixed, please review and merge.

**Comment by EvaKaul** [comment]
Approved the fix and merged to main.
